spring:
  config:
    activate:
      on-profile: "prod"

voting-ms:
  message: "Welcome to Vote service service related prod APIs "
  contactDetails:
    name: "Akermi Yahia - Product Owner"
    email: "ya.akermi@esi-sba.dz"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
